In [4]:
# wandb ids
# f8pvcd98: proba scale
# svodcpjl: log scale
# mqceg9d: mix scale

# read output files
import json
import pandas as pd
from new_module.dev_utils.utils import read_outputs

In [15]:
proba = read_outputs('/data/hyeryung/mucoco/outputs/sentiment/positive_gpt2/f8pvcd98/outputs_epsilon0.97.txt')
log = read_outputs('/data/hyeryung/mucoco/outputs/sentiment/positive_gpt2/svodcpjl/outputs_epsilon0.97.txt')
# mix = read_outputs('/data/hyeryung/mucoco/outputs/sentiment/positive_gpt2/mqceg9du/outputs_epsilon0.97.txt')

mix2 = read_outputs('/data/hyeryung/mucoco/outputs/sentiment/positive_gpt2/kvi2h6uo/outputs_epsilon0.97.txt.0')

In [17]:
for i in range(2):
    mix2[f'loss{i}'] = mix2['losses'].apply(lambda x: x[i])

In [18]:
for i in range(4):
    proba[f'loss{i}'] = proba['losses'].apply(lambda x: x[i])
    log[f'loss{i}'] = log['losses'].apply(lambda x: x[i])
    mix[f'loss{i}'] = mix['losses'].apply(lambda x: x[i])

In [ ]:
proba[['loss0', 'loss1', 'loss2', 'loss3']].abs().describe() # positive %: 86, CoLA: 0.47, BERT: 0.57, Edit: 8.06

            loss0       loss1       loss2       loss3
count  200.000000  200.000000  200.000000  200.000000
mean     0.043718    0.973840    0.593804    0.349670
std      0.030395    0.065204    0.157622    0.138492
min      0.000888    0.301729    0.053023    0.083333
25%      0.021823    0.974963    0.502311    0.250000
50%      0.039317    0.988301    0.607874    0.333333
75%      0.058177    0.995281    0.713387    0.428289
max      0.192852    0.999842    0.934691    0.750000

In [ ]:
log[['loss0', 'loss1', 'loss2', 'loss3']].abs().describe() # positive %: 81, CoLA: 0.74, BERTScore: 0.66, Edit: 6.72

            loss0       loss1       loss2       loss3
count  200.000000  200.000000  199.000000  200.000000
mean     2.619297    0.093969    0.453539    3.419490
std      0.475507    0.141806    0.333167    6.570537
min      1.504883    0.000299    0.000000    0.087011
25%      2.324219    0.020830    0.238008    0.906085
50%      2.613281    0.028159    0.394915    1.303983
75%      2.911621    0.116602    0.631707    1.734039
max      4.136719    0.879947    2.195910   23.025850

In [ ]:
mix[['loss0', 'loss1', 'loss2', 'loss3']].abs().describe() #

            loss0       loss1       loss2       loss3
count  200.000000  200.000000  200.000000  200.000000
mean     2.586836    0.088126    0.645501    0.314565
std      0.460044    0.129217    0.190731    0.175909
min      1.472656    0.000299    0.009684    0.000000
25%      2.314453    0.020375    0.521144    0.200000
50%      2.585938    0.028244    0.670122    0.296341
75%      2.883301    0.118940    0.766439    0.416667
max      3.994141    0.849222    1.000000    1.000000

In [20]:
mix2[['loss0', 'loss1']].abs().describe() #

            loss0       loss1
count  778.000000  778.000000
mean     2.655186    0.107651
std      0.494023    0.150097
min      1.310547    0.000242
25%      2.337891    0.021843
50%      2.577148    0.029989
75%      2.906250    0.145132
max      5.917969    1.088782