In [28]:
import pandas as pd
import numpy as np
from sklearn.metrics import (
    average_precision_score,
    f1_score,
    fbeta_score,
    precision_score,
    recall_score,
)

In [ ]:
def apply_recall(row, binary_labels_col:str, binary_preds_col:str):
    return recall_score(row[binary_labels_col],row[binary_preds_col], zero_division=np.nan)

In [43]:
labels = pd.read_json('/data/hyeryung/mucoco/new_module/data/NLI_locate/nli_contra_300_locate_labels.jsonl', lines=True)
labels = labels[['pairID', 'hypothesis_token_labels_binary']].copy()
use_energy_result = pd.read_json('/data/hyeryung/loc_edit/models/nli/roberta_large_snli_mnli_anli_train_dev_with_finegrained_finegrained_labels_cross_entropy_n_a/zgs9e2sr/nli_contra_300_locate_result_pearsonr_energy.jsonl', lines=True)
use_proba_result = pd.read_json('/data/hyeryung/loc_edit/models/nli/roberta_large_snli_mnli_anli_train_dev_with_finegrained_finegrained_labels_cross_entropy_n_a/zgs9e2sr/nli_contra_300_locate_result_pearsonr_proba.jsonl', lines=True)
# use_proba_result = pd.read_json('/data/hyeryung/loc_edit/models/nli/roberta_large_snli_mnli_anli_train_dev_with_finegrained_binary_labels_binary_cross_entropy_n_a/1731247443//nli_contra_300_locate_result_pearsonr_proba.jsonl', lines=True)
use_energy_result = pd.merge(labels, use_energy_result, on='pairID')
use_energy_result['recall'] = use_energy_result.apply(lambda x: apply_recall(x, 'hypothesis_token_labels_binary', 'hypothesis_token_pred_binary'), axis=1)
use_proba_result = pd.merge(labels, use_proba_result, on='pairID')
use_proba_result['recall'] = use_proba_result.apply(lambda x: apply_recall(x, 'hypothesis_token_labels_binary', 'hypothesis_token_pred_binary'), axis=1)
use_energy_result['num_mask'] = use_energy_result['hypothesis_token_pred_binary'].apply(sum)
use_proba_result['num_mask'] = use_proba_result['hypothesis_token_pred_binary'].apply(sum)
merged_result = pd.merge(use_proba_result[['pairID', 'recall', 'num_mask']], use_energy_result[['pairID', 'recall', 'num_mask']], on='pairID', suffixes=('_proba', '_energy'))
display(merged_result.loc[merged_result['recall_proba'] > merged_result['recall_energy'], ['recall_proba', 'recall_energy', 'num_mask_proba', 'num_mask_energy']])
display(merged_result.loc[merged_result['num_mask_proba'] > merged_result['num_mask_energy'],:])
display(merged_result.loc[merged_result['num_mask_proba'] < merged_result['num_mask_energy'],:])
display(merged_result.loc[merged_result['num_mask_proba'] == merged_result['num_mask_energy'],:])
use_energy_result['num_mask'].quantile([x/10 for x in range(11)])
use_proba_result['num_mask'].quantile([x/10 for x in range(11)])

     recall_proba  recall_energy  num_mask_proba  num_mask_energy
32       0.400000       0.300000               5                4
158      0.600000       0.400000               4                3
275      1.000000       0.500000               2                1
288      0.714286       0.571429               5                4

,pairID,recall_proba,num_mask_proba,recall_energy,num_mask_energy
19,6c9cd647-3cfe-4082-b0a0-d9676fb7f56e,1.000000,2,1.000000,1
24,d1e33f17-c341-4c35-81fd-c86f91bd1e69,1.000000,3,1.000000,2
32,bb9e4940-5bd5-48f5-ab21-020b06ad8140,0.400000,5,0.300000,4
94,8cf94791-8aef-4ce1-9416-2ff25828f3a4,0.500000,3,0.500000,2
103,44981c,1.000000,3,1.000000,2
158,24127c,0.600000,4,0.400000,3
162,92664c,0.500000,2,0.500000,1
181,91783c,0.333333,4,0.333333,3
189,8283c,0.666667,12,0.666667,11
191,68475c,0.666667,4,0.666667,3
244,370713359.jpg#1r1c,1.000000,3,1.000000,2
275,4814763982.jpg#3r1c,1.000000,2,0.500000,1
288,6198563920.jpg#1r1c,0.714286,5,0.571429,4
299,954987350.jpg#2r1c,0.666667,4,0.666667,3

Empty DataFrame
Columns: [pairID, recall_proba, num_mask_proba, recall_energy, num_mask_energy]
Index: []

,pairID,recall_proba,num_mask_proba,recall_energy,num_mask_energy
0,b137bf6e-dfb0-4a39-81a4-8ddb08d4f206,0.571429,9,0.571429,9
1,f17b5f80-e63c-4b53-9a8a-8217de0d9d6b,0.500000,3,0.500000,3
2,06e4ac13-7a10-4fbd-ab9f-628b36657056,0.400000,7,0.400000,7
3,b43998e6-f4af-4f4c-afe5-258493783355,1.000000,2,1.000000,2
4,f2e8f042-e7ae-476c-b5dc-7f5b584f5690,0.833333,7,0.833333,7
...,...,...,...,...,...
294,7466310132.jpg#2r1c,0.750000,3,0.750000,3
295,7537460976.jpg#1r1c,0.666667,2,0.666667,2
296,7788997944.jpg#3r1c,1.000000,2,1.000000,2
297,8077305139.jpg#0r1c,0.500000,3,0.500000,3
298,833459429.jpg#1r1c,1.000000,3,1.000000,3

0.0     1.0
0.1     2.0
0.2     2.0
0.3     2.0
0.4     3.0
0.5     3.0
0.6     3.0
0.7     4.0
0.8     5.0
0.9     6.0
1.0    12.0
Name: num_mask, dtype: float64

In [42]:
labels = pd.read_json('/data/hyeryung/mucoco/new_module/data/NLI_locate/nli_contra_300_locate_labels.jsonl', lines=True)
labels = labels[['pairID', 'hypothesis_token_labels_binary']].copy()
use_energy_result = pd.read_json('/data/hyeryung/loc_edit/models/nli/roberta_large_snli_mnli_anli_train_dev_with_finegrained_binary_labels_binary_cross_entropy_n_a/1731247443//nli_contra_300_locate_result_pearsonr_energy.jsonl', lines=True)
use_proba_result = pd.read_json('/data/hyeryung/loc_edit/models/nli/roberta_large_snli_mnli_anli_train_dev_with_finegrained_binary_labels_binary_cross_entropy_n_a/1731247443//nli_contra_300_locate_result_pearsonr_proba.jsonl', lines=True)

use_energy_result = pd.merge(labels, use_energy_result, on='pairID')
use_energy_result['recall'] = use_energy_result.apply(lambda x: apply_recall(x, 'hypothesis_token_labels_binary', 'hypothesis_token_pred_binary'), axis=1)
use_proba_result = pd.merge(labels, use_proba_result, on='pairID')
use_proba_result['recall'] = use_proba_result.apply(lambda x: apply_recall(x, 'hypothesis_token_labels_binary', 'hypothesis_token_pred_binary'), axis=1)
use_energy_result['num_mask'] = use_energy_result['hypothesis_token_pred_binary'].apply(sum)
use_proba_result['num_mask'] = use_proba_result['hypothesis_token_pred_binary'].apply(sum)
merged_result = pd.merge(use_proba_result[['pairID', 'recall', 'num_mask']], use_energy_result[['pairID', 'recall', 'num_mask']], on='pairID', suffixes=('_proba', '_energy'))
display(merged_result.loc[merged_result['recall_proba'] > merged_result['recall_energy'], ['recall_proba', 'recall_energy', 'num_mask_proba', 'num_mask_energy']])
display(merged_result.loc[merged_result['num_mask_proba'] > merged_result['num_mask_energy'],:])
display(merged_result.loc[merged_result['num_mask_proba'] < merged_result['num_mask_energy'],:])
display(merged_result.loc[merged_result['num_mask_proba'] == merged_result['num_mask_energy'],:])
# use_energy_result['num_mask'].quantile([x/10 for x in range(11)])
# use_proba_result['num_mask'].quantile([x/10 for x in range(11)])

     recall_proba  recall_energy  num_mask_proba  num_mask_energy
8        1.000000       0.500000               2                1
11       0.666667       0.333333               5                3
35       0.600000       0.400000               5                4
41       0.500000       0.250000               3                2
68       0.600000       0.400000               3                2
115      0.666667       0.333333               3                2
158      0.400000       0.200000               4                3
254      0.750000       0.500000               3                2

,pairID,recall_proba,num_mask_proba,recall_energy,num_mask_energy
1,f17b5f80-e63c-4b53-9a8a-8217de0d9d6b,0.500000,5,0.500000,3
8,4833c3b7-7677-4850-9b8d-3d734d657926,1.000000,2,0.500000,1
11,d04a0283-3889-48bd-9d8e-821b03512780,0.666667,5,0.333333,3
30,e565857b-e5b5-42a5-ab27-514f9e6a463b,0.750000,5,0.750000,4
35,746a560d-16e8-4b47-996f-fc2e6b3da9a2,0.600000,5,0.400000,4
41,fdcd3ead-9143-4ae8-b412-9c0ffae77906,0.500000,3,0.250000,2
47,8f08a187-e6af-4581-87f3-8766acd476dd,1.000000,10,1.000000,9
68,f99c2936-1ca0-4211-a750-44ecf7c632f8,0.600000,3,0.400000,2
80,8fa7bb15-dece-44da-bcd4-e5d926679d67,0.000000,5,0.000000,4
115,43006c,0.666667,3,0.333333,2
153,139779c,0.400000,5,0.400000,4
158,24127c,0.400000,4,0.200000,3
175,125272c,0.200000,4,0.200000,3
191,68475c,1.000000,4,1.000000,3
239,3576445378.jpg#0r1n,0.400000,4,0.400000,3
254,4045308081.jpg#0r1c,0.750000,3,0.500000,2
275,4814763982.jpg#3r1c,0.500000,2,0.500000,1
281,4923472130.jpg#2r1c,1.000000,3,1.000000,2
291,6489895665.jpg#1r1c,0.500000,4,0.500000,3

    pairID  recall_proba  num_mask_proba  recall_energy  num_mask_energy
188  5637c           1.0               4            1.0                5

,pairID,recall_proba,num_mask_proba,recall_energy,num_mask_energy
0,b137bf6e-dfb0-4a39-81a4-8ddb08d4f206,0.428571,8,0.428571,8
2,06e4ac13-7a10-4fbd-ab9f-628b36657056,0.400000,6,0.400000,6
3,b43998e6-f4af-4f4c-afe5-258493783355,1.000000,2,1.000000,2
4,f2e8f042-e7ae-476c-b5dc-7f5b584f5690,0.833333,7,0.833333,7
5,0569f5f7-56d3-46c7-a3d8-7e894964ea0a,0.666667,2,0.666667,2
...,...,...,...,...,...
295,7537460976.jpg#1r1c,0.666667,2,0.666667,2
296,7788997944.jpg#3r1c,1.000000,2,1.000000,2
297,8077305139.jpg#0r1c,0.500000,3,0.500000,3
298,833459429.jpg#1r1c,1.000000,3,1.000000,3
299,954987350.jpg#2r1c,0.666667,4,0.666667,4